apiVersion: v1
kind: Pod
metadata:
  name: attacker
  labels:
    app: attacker
spec:
  containers:
  - name: attacker
    image: docker.io/bitnami/minideb:latest
    command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
    securityContext:
      runAsUser: 1000
      readOnlyRootFilesystem: true
  restartPolicy: Never

